server:
  port: 8082
spring:
  application:
    name: payment-risk-engine
  kafka:
    consumer:
      bootstrap-servers:
       - localhost:9092  
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer  
      auto-offset-reset: latest
risk:
  engiene:
    service:
      url: https://blabla/api/v3/check-risk