server:
  port: 8082
spring:
  application:
    name: payment-risk-engine
  kafka:
    consumer:
      groupId: payment-group
      topic: payment-topic
      bootstrap-servers: localhost:9092  
#   
    
