server:
  port: 8082
spring:
  application:
    name: payment-risk-engine
  kafka:
    consumer:
      groupId: payment-group
      topic: payment-topic
      bootstrap-servers: localhost:9092  
risk.engiene.service.url: https://payment-risk:8080/api/v1/check   
    
