server:
  port: 8081
spring:
  application:
    name: payment-service
  kafka:
    producer:
      bootstrap-servers:       - localhost:9092  
      key-serializer: org.springframework.kafka.support.serializer.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer  
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/payment-system
    username: user
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

